name: CI

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: ./node_modules/.bin/mocha

  eslint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
